<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsTestProject>true</IsTestProject>
        <RootNamespace>Broccoli.Avalonia.Tests</RootNamespace>
        <NoWarn>$(NoWarn);CA2201;CA1510;CA1511;CA1512;CA1513</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Moq" />
        <PackageReference Include="MSTest.TestAdapter" />
        <PackageReference Include="MSTest.TestFramework" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../Broccoli.Avalonia/Broccoli.Avalonia.csproj" />
    </ItemGroup>

</Project>
