// <auto-generated />
using System;
using Broccoli.Avalonia.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Broccoli.Avalonia.Storage.Migrations
{
    [DbContext(typeof(BroccoliDbContext))]
    [Migration("20260823015754_AddAutoBalanceStrategy")]
    partial class AddAutoBalanceStrategy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Broccoli.Avalonia.Models.DailyFoodPlan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<string>("Tabs")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("tabs");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("userId");

                    b.HasKey("Id");

                    b.ToTable("DailyFoodPlans");
                });

            modelBuilder.Entity("Broccoli.Avalonia.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<double>("CaloriesPer100g")
                        .HasColumnType("REAL");

                    b.Property<double>("CarbohydratesPer100g")
                        .HasColumnType("REAL");

                    b.Property<double>("DietaryFiberPer100g")
                        .HasColumnType("REAL");

                    b.Property<double>("FatPer100g")
                        .HasColumnType("REAL");

                    b.Property<double>("GramsPerMeasure")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ProteinPer100g")
                        .HasColumnType("REAL");

                    b.Property<double>("SaturatedFatPer100g")
                        .HasColumnType("REAL");

                    b.Property<double>("SodiumMgPer100g")
                        .HasColumnType("REAL");

                    b.Property<double>("SugarsPer100g")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("Broccoli.Avalonia.Models.GroceryListItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("createdAt");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("isChecked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("partitionKey");

                    b.Property<string>("QuantityHint")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("userId");

                    b.HasKey("Id");

                    b.ToTable("GroceryListItems");
                });

            modelBuilder.Entity("Broccoli.Avalonia.Models.MacroTarget", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("activityLevel");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("age");

                    b.Property<double>("Bmr")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("bmr");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("createdAt");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("gender");

                    b.Property<int>("Goal")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("goal");

                    b.Property<int>("GoalCalorieDelta")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("goalCalorieDelta");

                    b.Property<double>("HeightCm")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("heightCm");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("partitionKey");

                    b.Property<double>("RecommendedCalories")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("recommendedCalories");

                    b.Property<double>("RecommendedCarbsG")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("recommendedCarbsG");

                    b.Property<double>("RecommendedFatG")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("recommendedFatG");

                    b.Property<double>("RecommendedProteinG")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("recommendedProteinG");

                    b.Property<double>("Tdee")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("tdee");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("userId");

                    b.Property<double>("WeightKg")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("weightKg");

                    b.HasKey("Id");

                    b.ToTable("MacroTargets");
                });

            modelBuilder.Entity("Broccoli.Avalonia.Models.MacroTargetSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<int>("AutoBalanceStrategy")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("autoBalanceStrategy");

                    b.Property<int>("BmrFormula")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("bmrFormula");

                    b.Property<double>("CalorieMatchTolerancePercent")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("calorieMatchTolerancePercent");

                    b.Property<double>("CarbPercent")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("carbPercent");

                    b.Property<double>("FatPercent")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("fatPercent");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("partitionKey");

                    b.Property<double>("ProteinGramsPerKg")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("proteinGramsPerKg");

                    b.Property<int>("ProteinMethod")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("proteinMethod");

                    b.Property<double>("ProteinPercent")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("proteinPercent");

                    b.Property<int>("RecipeHistoryBackupCount")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("recipeHistoryBackupCount");

                    b.Property<bool>("RecipeMealComparisonEnabled")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("recipeMealComparisonEnabled");

                    b.Property<string>("RecipeMealComparisonPersonId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("recipeMealComparisonPersonId");

                    b.Property<bool>("ShowCardCalorieMatch")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("showCardCalorieMatch");

                    b.Property<bool>("ShowCardImage")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("showCardImage");

                    b.Property<bool>("ShowCardNutrition")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("showCardNutrition");

                    b.Property<bool>("ShowCardSeasonality")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("showCardSeasonality");

                    b.Property<bool>("ShowCardTags")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("showCardTags");

                    b.Property<bool>("ShowSeasonalityNavItem")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("showSeasonalityNavItem");

                    b.Property<int>("UnitSystem")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("unitSystem");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("userId");

                    b.HasKey("Id");

                    b.ToTable("MacroTargetSettings");
                });

            modelBuilder.Entity("Broccoli.Avalonia.Models.MealPrepPlan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<string>("RecipeIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("recipeIds");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("sortOrder");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("userId");

                    b.HasKey("Id");

                    b.ToTable("MealPrepPlans");
                });

            modelBuilder.Entity("Broccoli.Avalonia.Models.PantryItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("partitionKey");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("userId");

                    b.HasKey("Id");

                    b.ToTable("PantryItems");
                });

            modelBuilder.Entity("Broccoli.Avalonia.Models.ProduceItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<string>("Months")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("months");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("notes");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("type");

                    b.HasKey("Id");

                    b.ToTable("ProduceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
