// <auto-generated />
using System;
using Broccoli.Avalonia.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Broccoli.Avalonia.Storage.Migrations
{
    [DbContext(typeof(BroccoliDbContext))]
    [Migration("20260725082058_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Broccoli.Data.Models.DailyFoodPlan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<string>("Tabs")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("tabs");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("userId");

                    b.HasKey("Id");

                    b.ToTable("DailyFoodPlans");
                });

            modelBuilder.Entity("Broccoli.Data.Models.GroceryListItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("createdAt");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("isChecked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("partitionKey");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("userId");

                    b.HasKey("Id");

                    b.ToTable("GroceryListItems");
                });

            modelBuilder.Entity("Broccoli.Data.Models.MacroTarget", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("activityLevel");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("age");

                    b.Property<double>("Bmr")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("bmr");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("createdAt");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("gender");

                    b.Property<int>("Goal")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("goal");

                    b.Property<int>("GoalCalorieDelta")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("goalCalorieDelta");

                    b.Property<double>("HeightCm")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("heightCm");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("partitionKey");

                    b.Property<double>("RecommendedCalories")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("recommendedCalories");

                    b.Property<double>("RecommendedCarbsG")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("recommendedCarbsG");

                    b.Property<double>("RecommendedFatG")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("recommendedFatG");

                    b.Property<double>("RecommendedProteinG")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("recommendedProteinG");

                    b.Property<double>("Tdee")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("tdee");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("userId");

                    b.Property<double>("WeightKg")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("weightKg");

                    b.HasKey("Id");

                    b.ToTable("MacroTargets");
                });

            modelBuilder.Entity("Broccoli.Data.Models.MacroTargetSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<int>("BmrFormula")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("bmrFormula");

                    b.Property<double>("CarbPercent")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("carbPercent");

                    b.Property<double>("FatPercent")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("fatPercent");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("partitionKey");

                    b.Property<double>("ProteinGramsPerKg")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("proteinGramsPerKg");

                    b.Property<int>("ProteinMethod")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("proteinMethod");

                    b.Property<double>("ProteinPercent")
                        .HasColumnType("REAL")
                        .HasJsonPropertyName("proteinPercent");

                    b.Property<bool>("RecipeMealComparisonEnabled")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("recipeMealComparisonEnabled");

                    b.Property<string>("RecipeMealComparisonPersonId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("recipeMealComparisonPersonId");

                    b.Property<int>("UnitSystem")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("unitSystem");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("userId");

                    b.HasKey("Id");

                    b.ToTable("MacroTargetSettings");
                });

            modelBuilder.Entity("Broccoli.Data.Models.MealPrepPlan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<string>("RecipeIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("recipeIds");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("sortOrder");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("userId");

                    b.HasKey("Id");

                    b.ToTable("MealPrepPlans");
                });

            modelBuilder.Entity("Broccoli.Data.Models.PantryItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("id");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER")
                        .HasJsonPropertyName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("createdAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("name");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("partitionKey");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasJsonPropertyName("userId");

                    b.HasKey("Id");

                    b.ToTable("PantryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
